# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-26 17:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='date_of_meeting',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
